"""Source asset discovery, resolution, inspection, and tool adapters."""

from .limits import MAX_STUDIO_MATERIALS, MAX_STUDIO_SKIN_FAMILIES

from .searchpaths import (
    AssetProvenance,
    MountedSearchPath,
    OrderedAssetFileSystem,
    ResolvedAsset,
    SearchPathDiagnostic,
    SearchPathParseError,
    SearchPathPlan,
    SearchPathSpec,
    normalize_logical_path,
    parse_gameinfo_search_paths,
    parse_search_paths_text,
    plan_search_paths,
)
from .mdl import (
    MaterialReferenceMetadata,
    SourceAssetInspectionError,
    SourceAssetMetadata,
    SourceFileMetadata,
    inspect_source_model,
)
from .vmt import (
    ColorParameter,
    MaterialBlockMetadata,
    SourceMaterialFileMetadata,
    SourceMaterialInspectionError,
    SourceMaterialMetadata,
    colored_material_path,
    inspect_source_material,
    select_color_parameter,
)
from .vmt_generation import (
    ColorAssignment,
    GeneratedMaterialContent,
    MaterialGenerationError,
    MaterialGenerationMode,
    generate_colored_material,
)
from .qc import (
    QCTransformError,
    QCTransformResult,
    SourceQCMetadata,
    build_reference_qc,
    build_scaled_qc,
    first_body_reference_smd,
    inspect_qc,
    static_bodygroup_empty_smd_name,
)
from .smd import SMDTransformError, build_empty_bodygroup_smd
from .toolchain import (
    CompiledFileMetadata,
    CompiledModelValidation,
    CompiledModelValidationError,
    CrowbarDecompileResult,
    ToolExecutionError,
    ToolInvocation,
    run_crowbar_decompile,
    run_studiomdl_compile,
    validate_compiled_model,
)

__all__ = [
    "AssetProvenance",
    "ColorParameter",
    "ColorAssignment",
    "CompiledFileMetadata",
    "CompiledModelValidation",
    "CompiledModelValidationError",
    "CrowbarDecompileResult",
    "GeneratedMaterialContent",
    "MaterialReferenceMetadata",
    "MaterialBlockMetadata",
    "MaterialGenerationError",
    "MaterialGenerationMode",
    "MAX_STUDIO_MATERIALS",
    "MAX_STUDIO_SKIN_FAMILIES",
    "MountedSearchPath",
    "OrderedAssetFileSystem",
    "QCTransformError",
    "QCTransformResult",
    "ResolvedAsset",
    "SearchPathDiagnostic",
    "SearchPathParseError",
    "SearchPathPlan",
    "SearchPathSpec",
    "SMDTransformError",
    "SourceAssetInspectionError",
    "SourceAssetMetadata",
    "SourceFileMetadata",
    "SourceMaterialFileMetadata",
    "SourceMaterialInspectionError",
    "SourceMaterialMetadata",
    "SourceQCMetadata",
    "ToolExecutionError",
    "ToolInvocation",
    "build_reference_qc",
    "build_scaled_qc",
    "build_empty_bodygroup_smd",
    "colored_material_path",
    "generate_colored_material",
    "first_body_reference_smd",
    "inspect_source_material",
    "inspect_source_model",
    "inspect_qc",
    "normalize_logical_path",
    "parse_gameinfo_search_paths",
    "parse_search_paths_text",
    "plan_search_paths",
    "run_crowbar_decompile",
    "run_studiomdl_compile",
    "select_color_parameter",
    "static_bodygroup_empty_smd_name",
    "validate_compiled_model",
]
